### ISSUE TITLE
Default color not being applied to color picker

### ISSUE THREAD

**Issue by thetwopct** [garciaalvaro/post-meta-controls#5] opened 2020-11-12 10:35 UTC
I've noticed if setting a default color for the color picker, it isn't set in the editor:

```
array(
 'type'          => 'color',
 'data_type'     => 'meta',
 'data_key'      => 'overlay_color',
 'label'         => __( 'Color Overlay' ),
 'help'          => __( 'Chose a color to overlay the background image' ),
 'register_meta' => true,
 'ui_border_top' => true,
 'default_value' => '#000AAA',
 'alpha_control' => true,
 'palette'       => $palette,
),
```

and in the editor:

<img width="279" alt="2020-11-12-113102@2x" src="https://user-images.githubusercontent.com/10615884/98928871-9a972800-24da-11eb-90b8-b042001a1c37.png">

I've tried different variations of the color value (rgba, a name matching the palette, hex code with hash) but none work.

**Comment by garciaalvaro** [comment] 2020-11-14 12:55
Hi, thanks for reporting.

I can confirm the bug. The problem is in the sanitize function used for the default value of the color setting, which is too strict. Currently I am working in a refactor so could take some time to make a new release. But [this commit](https://github.com/garciaalvaro/post-meta-controls/commit/5aa62d2939dead9c97c5ce9e54b96b5795793738) in the develop branch has the fix for the bug.

**Comment by thetwopct** [comment] 2020-11-14 13:16
Awesome thanks, I’ll update my version to fix while awaiting the update. Thanks for swift response and great plugin 🙏🏼

**Comment by garciaalvaro** [comment] 2020-11-14 14:55
You are welcome, I'm glad you like the plugin :)
I am going to close this issue and will comment here once it's ready.

**Closed by garciaalvaro** 2020-11-14 14:55 UTC

**Comment by garciaalvaro** [comment] 2020-12-09 22:49
The latest release (1.3.4) contains the fix for this issue.

Thanks
